### ISSUE TITLE
Take care of main page touchups

### ISSUE THREAD

**Issue by crertel** [RoboticSwarmControl/SwarmControlRedux#25]
- Main page: The G+1 and Facebook lik icon are not aligned
- Main page: Robot positioning icon the green lines are the wrong color – too bright and hard to see. Never noticed that before

**Comment by crertel** [comment]
@aabecker Question about the robot positioning icon--could you elaborate on the lines? It looks fine over here--maybe we just want to thicken the circles some?

Also, can we switch the social media buttons to just be simple links instead of including the counts? That'll decrease the requirement to have extra scripts loading and whatnot, which should improve performance and layout.

**Comment by crertel** [comment]
@aabecker I've gotten the icons lining up, so this is mergable, but in the future we might still want to trim them down a bit as described above.

**Comment by aabecker** [comment]
OK with removing counts. Have to look at site again for the icon

**Comment by crertel** [comment]
This will be fixed in PR #28.
