### ISSUE TITLE
Final polish and first production release

### ISSUE THREAD

**Issue by crertel** [RoboticSwarmControl/SwarmControlRedux#44]
We're finally almost ready to go live!

Last couple of things to check:

* Make sure that the most recent game results (for the user) are stored either in localStorage or are at least being detected properly from the returned result
* Check out a report that the stars might not be updating proeprly.
* Add another "Accept Terms" button to the ToS splash
* Push it live.

**Comment by crertel** [comment]
So, investigating the stars, it looks like the `robot-positiong` game is fine, but the `pyramid-building` game seems to only display the star on the main screen, and not on the post-game wrapup.

**Comment by crertel** [comment]
(work is being done on branch `44-final-polish`)

**Comment by crertel** [comment]
So, fixed the stars not showing up. It appeared to be a weird interaction between:

* The way the participant string was being extracted from the cookie
* A race condition where results could be fetched before the new result had been posted.

This now seems to be fixed in local testing--testing in staging next.

**Comment by crertel** [comment]
Confirmed fixed on staging server--with fresh cookies, all tasks register the first start correctly now. Next is going to be fixing the "latest result" bit.

**Comment by crertel** [comment]
Fixed the stars and results for the participant counts not lining up. Fixed now!

**Comment by aabecker** [comment]
Can you go live?

*Aaron T. Becker*

Assistant Professor of Electrical & Computer Engineering, University of
Houston
youtube.com/aabecker5/

**Comment by crertel** [comment]
Going live once this is merged!

**Comment by crertel** [comment]
Fixed ToS needing second accept. Opened and merged PR #45.

**Comment by crertel** [comment]
Aaaand we're live!

Note that we had to set it to use the [new cedar-14 stack on Heroku](https://devcenter.heroku.com/articles/cedar-14-migration)  and to use the dev environment for npm to install the dependencies [properly](http://stackoverflow.com/questions/22954782/install-devdependencies-on-heroku).

**Comment by crertel** [comment]
Closing the ticket, and I'll start fixing the graph drawing next.
